import React from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  const testApi = React.useCallback(async () => {
    const data = await fetch("/api/date");
    console.log(await data.text());
  });

  const [features, setFeatures] = React.useState({ liga: 0, zero: 0 });

  const settings = Object.entries(features)
    .map(([f, val]) => `"${f}" ${val ? 1 : 0}`)
    .join(", ");

  const downloadUrl = Object.entries(features)
    .map(([f, val]) => `${f}=${val ? 1 : 0}`)
    .join("&");

  return (
    <div className={styles.container}>
      <Head>
        <title>Fonts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <div>
            <input
              type="checkbox"
              id="liga"
              name="liga"
              checked={features.liga}
              onChange={() =>
                setFeatures({ ...features, liga: features.liga ? 0 : 1 })
              }
            />
            <label htmlFor="liga">Ligatures</label>
          </div>

          <div>
            <input
              type="checkbox"
              id="zero"
              name="zero"
              checked={features.zero}
              onChange={() =>
                setFeatures({ ...features, zero: features.zero ? 0 : 1 })
              }
            />
            <label htmlFor="zero">Zero</label>
          </div>
        </div>

        <div>
          <div
            style={{
              fontFamily: "TestCustomized",
              fontFeatureSettings: settings
            }}
          >
            0 ->
          </div>
        </div>

        <div><a href={`/api/font/?${downloadUrl}`}>Download</a></div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
